import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Card from '../components/card'
import Header from '../components/header/header'
import styles from '../styles/Home.module.css'
import book1 from "../public/book1_elon.jpg";
import book2 from "../public/book2_john.jpg";
import book3 from "../public/book3_daniel.jpg";
import book4 from "../public/book4_robert.jpg";
import book5 from "../public/book5_warren.jpg";
import book6 from "../public/book6_thibaut.jpg";
import book7 from "../public/book7_ikigai.jpg";
import book8 from "../public/book8_ian.jpg";
import book9 from "../public/book9_michael.jpg";
import book10 from "../public/book10_robert.jpg";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home Page</title>
      </Head>
      <Header />
      <div className="container">
        <h1 className='my-4'>Top 10 Books of 2022</h1>
        <Card image={book1} imageAlt="The Life, Lessons & Rules For Success" bookTitle="Elon Musk: The Life, Lessons & Rules For Success" bookDescription="The book is about how Musk' insistence on setting the standard rather than following everyone else in the traditional path, made him successful.Another remarkable thing about Musk and his life story, is his quest to find a greater purpose in what he is doing.Successful people never stop learning, and Musk is the best example of this characteristic.Great to read about Musk's life from 34000 USD to become Billionaire." bookLink='https://www.amazon.ca/Elon-Musk-Lessons-Rules-Success/dp/1973364700/ref=asc_df_1973364700/?tag=googleshopc0c-20&linkCode=df0&hvadid=335330317605&hvpos=&hvnetw=g&hvrand=7368940942219337426&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9000839&hvtargid=pla-417622046543&psc=1' />
        <Card image={book2} imageAlt="The Power of Letting Go" bookTitle="The Power of Letting Go" bookDescription="The Power of Letting Gobrings together a number of key principles that come up for anyone who is on the journey of self-enquiry and development. At some point, the choice becomes clear, whether to hold on or let go.For some, it''s easy, just do it, f**k it.For many others, there are multiple layers and obstacles that have built up through one''s life so far.This book combines both the why and the how to let go, with excellent practices that help convert the desire into action." bookLink='https://www.audible.ca/pd/The-Power-of-Letting-Go-Audiobook/1783253940?ipRedirectOverride=true&overrideBaseCountry=true&bp_o=true&source_code=HavGB1270222210046&gclid=CjwKCAjw9qiTBhBbEiwAp-GE0cVKgeVH4dHcL5Eny-nWvD_k-5HIB7B8WtPkvM0qBwff-AUlFmNYBxoCl3gQAvD_BwE&gclsrc=aw.ds' />
        <Card image={book3} imageAlt="Thinking, Fast and Slow" bookTitle="Thinking, Fast and Slow" bookDescription="The book's main thesis is that of a dichotomy between two modes of thought:'System 1' is fast, instinctive and emotional; 'System 2' is slower, more deliberative, and more logical. The integrity of many of the priming studies cited in the book have been called into question in the midst of the psychological replication crisis, although the results of Kahneman's own studies have been replicated. The book was a New York Times bestseller[4] and won the 2012 winner of the National Academies Communication Award for best creative work that helps the public understanding of topics in behavioral science, engineering and medicine." bookLink='https://www.amazon.ca/Thinking-Fast-Slow-Daniel-Kahneman/dp/0385676530/ref=asc_df_0385676530/?tag=googleshopc0c-20&linkCode=df0&hvadid=293014791721&hvpos=&hvnetw=g&hvrand=7368940942219337426&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9000839&hvtargid=pla-499612622557&psc=1' />
        <Card image={book4} imageAlt="The 48 Laws of Power" bookTitle="The 48 Laws of Power" bookDescription="The 48 Laws of Power (1998) is a non-fiction book by American author Robert Greene. The book is a New York Times bestseller, selling over 1.2 million copies in the United States, and is popular with prison inmates and celebrities." bookLink='https://www.amazon.ca/48-Laws-Power-Robert-Greene/dp/0140280197/ref=asc_df_0140280197/?tag=googleshopc0c-20&linkCode=df0&hvadid=292967644263&hvpos=&hvnetw=g&hvrand=7368940942219337426&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9000839&hvtargid=pla-433843038144&psc=1' />
        <Card image={book5} imageAlt="The Warren Buffett Way" bookTitle="The Warren Buffett Way: Investment Strategies of the World's Greatest Investor" bookDescription="The runaway bestseller-updated with new material included for the first time! The Warren Buffett Way outlines his career and presents examples of how his investment techniques and methods evolved and the important individuals in that process. It also details the key investment decisions that produced his unmatched record of performance." bookLink='https://www.audible.ca/pd/The-Warren-Buffett-Way-Audiobook/B0725N15Z9?ipRedirectOverride=true&overrideBaseCountry=true&bp_o=true&source_code=HavGB1270222210046&gclid=CjwKCAjw9qiTBhBbEiwAp-GE0ahU5-qeRQxvJJgzh2WAIyqc-uUkPNaL2gHvBL8FU_MT5vpS6Opq9RoCALgQAvD_BwE&gclsrc=aw.ds' />
        <Card image={book6} imageAlt="Master Your Emotions" bookTitle="Master Your Emotions: A Practical Guide to Overcome Negativity and Better Manage Your Feelings" bookDescription="Struggling to let go of negative emotions? Discover a step-by-step process to living a happier, more fulfilling life. Weighed down by negativity? Are painful emotions keeping you from doing the things you love? Author and founder of WhatIsPersonalDevelopment.org Thibaut Meurisse wants to help you take back your life." bookLink='https://www.amazon.ca/Master-Your-Emotions-Practical-Negativity/dp/1981089152/ref=asc_df_1981089152/?tag=googleshopc0c-20&linkCode=df0&hvadid=292914274695&hvpos=&hvnetw=g&hvrand=7368940942219337426&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9000839&hvtargid=pla-523968824816&psc=1' />
        <Card image={book7} imageAlt="Ikigai" bookTitle="Ikigai: The Japanese Secret to a Long and Happy Life" bookDescription="The people of Japan believe that everyone has an ikigai – a reason to jump out of bed each morning. And according to the residents of the Japanese island of Okinawa – the world’s longest-living people – finding it is the key to a longer and more fulfilled life. Inspiring and comforting, this book will give you the life-changing tools to uncover your personal ikigai." bookLink='https://www.amazon.ca/Ikigai-Japanese-Secret-Long-Happy/dp/0143130722/ref=asc_df_0143130722/?tag=googleshopc0c-20&linkCode=df0&hvadid=309344616184&hvpos=&hvnetw=g&hvrand=7368940942219337426&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9000839&hvtargid=pla-395221952140&psc=1' />
        <Card image={book8} imageAlt="The Power of Mental Discipline" bookTitle="The Power of Mental Discipline" bookDescription="Create the life of your dreams. Break your old habits, become unstoppable and dominate your life!Imagine – your life as a blank slate. You can choose what you want it to look like. Like a video game, you can fill it with whatever you like!" bookLink='https://www.amazon.ca/Power-Mental-Discipline-Controlling-Increasing/dp/1696742382/ref=asc_df_1696742382/?tag=googleshopc0c-20&linkCode=df0&hvadid=335136579009&hvpos=&hvnetw=g&hvrand=7368940942219337426&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9000839&hvtargid=pla-828546767979&psc=1' />
        <Card image={book9} imageAlt="The First 90 Days" bookTitle="The First 90 Days: Critical Success Strategies for New Leaders at All Levels" bookDescription="Since its original release, The First 90 Days has become the bestselling globally acknowledged bible of leadership and career transitions. In this updated and expanded 10th anniversary edition, internationally known leadership transition expert Michael D. Watkins gives you the keys to successfully negotiating your next move—whether you’re onboarding into a new company, being promoted internally, or embarking on an international assignment." bookLink='https://www.amazon.ca/First-Days-Updated-Expanded-Strategies/dp/1422188612/ref=asc_df_1422188612/?tag=googleshopc0c-20&linkCode=df0&hvadid=292914274695&hvpos=&hvnetw=g&hvrand=7368940942219337426&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9000839&hvtargid=pla-404766147599&psc=1' />
        <Card image={book10} imageAlt="Rich Dad, Poor Dad" bookTitle="Rich Dad, Poor Dad" bookDescription="Rich Dad Poor Dad is Robert's story of growing up with two dads — his real father and the father of his best friend, his'rich dad' — and the ways in which both men shaped his thoughts about money and investing. The book explodes the myth that you need to earn a high income to be rich and explains the difference between working for money and having your money work for you." bookLink='https://www.amazon.ca/Rich-Dad-Poor-Teach-Middle/dp/1612680194/ref=asc_df_1612680194/?tag=googleshopc0c-20&linkCode=df0&hvadid=292914274695&hvpos=&hvnetw=g&hvrand=7368940942219337426&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9000839&hvtargid=pla-301634461823&psc=1' />
      </div>
    </>
  )
}

export default Home
